"""Stub: System.Collections.Generic.List (pythonnet, не stdlib list)."""

from typing import Iterator

class List:
    def __init__(self) -> None: ...
    def __class_getitem__(cls, item: type) -> type[List]: ...
    def Add(self, item: object) -> None: ...
    @property
    def Count(self) -> int: ...
    def __getitem__(self, index: int) -> object: ...
    def __iter__(self) -> Iterator[object]: ...
