# src/pydajet_metadata/protocols.py
"""Протоколы для типизации динамических атрибутов Query."""

from typing import Protocol, runtime_checkable
from sqlalchemy.sql.elements import BinaryExpression


@runtime_checkable
class ColumnAccessor(Protocol):
    """Протокол доступа к колонкам через точку."""

    def __eq__(self, other: object) -> BinaryExpression: ...
    def __ne__(self, other: object) -> BinaryExpression: ...
    def __gt__(self, other: object) -> BinaryExpression: ...
    def __lt__(self, other: object) -> BinaryExpression: ...
    def __ge__(self, other: object) -> BinaryExpression: ...
    def __le__(self, other: object) -> BinaryExpression: ...
    def like(self, other: str) -> BinaryExpression: ...
    def in_(self, other: list) -> BinaryExpression: ...
    def between(self, low, high) -> BinaryExpression: ...
